(define (problem patrol-18-p05)
 (:domain patrol2)
 (:objects
  city-loc-1 - location
  city-loc-2 - location
  city-loc-3 - location
  city-loc-4 - location
  city-loc-5 - location
  city-loc-6 - location
  city-loc-7 - location
  city-loc-8 - location
  city-loc-9 - location
  city-loc-10 - location
  city-loc-11 - location
  city-loc-12 - location
  city-loc-13 - location
  city-loc-14 - location
  city-loc-15 - location
  n0 - num
  n1 - num
  n2 - num
  n3 - num
  n4 - num
  n5 - num
  n6 - num
  n7 - num
  n8 - num
  n9 - num
  n10 - num
  n11 - num
  n12 - num
  n13 - num
  n14 - num
  n15 - num
  n16 - num
  n17 - num
  n18 - num
 )
 (:init
 (= (total-cost) 0)
  (succesor n0 n1)
  (succesor n1 n2)
  (succesor n2 n3)
  (succesor n3 n4)
  (succesor n4 n5)
  (succesor n5 n6)
  (succesor n6 n7)
  (succesor n7 n8)
  (succesor n8 n9)
  (succesor n9 n10)
  (succesor n10 n11)
  (succesor n11 n12)
  (succesor n12 n13)
  (succesor n13 n14)
  (succesor n14 n15)
  (succesor n15 n16)
  (succesor n16 n17)
  (succesor n17 n18)
  (max-steps n18)
  (road city-loc-4 city-loc-1)
  (road city-loc-1 city-loc-4)
  (road city-loc-4 city-loc-2)
  (road city-loc-2 city-loc-4)
  (road city-loc-5 city-loc-2)
  (road city-loc-2 city-loc-5)
  (road city-loc-5 city-loc-3)
  (road city-loc-3 city-loc-5)
  (road city-loc-6 city-loc-5)
  (road city-loc-5 city-loc-6)
  (road city-loc-7 city-loc-2)
  (road city-loc-2 city-loc-7)
  (road city-loc-7 city-loc-3)
  (road city-loc-3 city-loc-7)
  (road city-loc-7 city-loc-4)
  (road city-loc-4 city-loc-7)
  (road city-loc-7 city-loc-5)
  (road city-loc-5 city-loc-7)
  (road city-loc-9 city-loc-7)
  (road city-loc-7 city-loc-9)
  (road city-loc-9 city-loc-8)
  (road city-loc-8 city-loc-9)
  (road city-loc-10 city-loc-3)
  (road city-loc-3 city-loc-10)
  (road city-loc-11 city-loc-6)
  (road city-loc-6 city-loc-11)
  (road city-loc-12 city-loc-2)
  (road city-loc-2 city-loc-12)
  (road city-loc-12 city-loc-4)
  (road city-loc-4 city-loc-12)
  (road city-loc-12 city-loc-5)
  (road city-loc-5 city-loc-12)
  (road city-loc-12 city-loc-7)
  (road city-loc-7 city-loc-12)
  (road city-loc-13 city-loc-2)
  (road city-loc-2 city-loc-13)
  (road city-loc-13 city-loc-5)
  (road city-loc-5 city-loc-13)
  (road city-loc-13 city-loc-6)
  (road city-loc-6 city-loc-13)
  (road city-loc-14 city-loc-2)
  (road city-loc-2 city-loc-14)
  (road city-loc-14 city-loc-3)
  (road city-loc-3 city-loc-14)
  (road city-loc-14 city-loc-5)
  (road city-loc-5 city-loc-14)
  (road city-loc-14 city-loc-6)
  (road city-loc-6 city-loc-14)
  (road city-loc-14 city-loc-7)
  (road city-loc-7 city-loc-14)
  (road city-loc-14 city-loc-13)
  (road city-loc-13 city-loc-14)
  (road city-loc-15 city-loc-3)
  (road city-loc-3 city-loc-15)
  (road city-loc-15 city-loc-5)
  (road city-loc-5 city-loc-15)
  (road city-loc-15 city-loc-6)
  (road city-loc-6 city-loc-15)
  (road city-loc-15 city-loc-10)
  (road city-loc-10 city-loc-15)
  (road city-loc-15 city-loc-11)
  (road city-loc-11 city-loc-15)
  (road city-loc-15 city-loc-13)
  (road city-loc-13 city-loc-15)
  (road city-loc-15 city-loc-14)
  (road city-loc-14 city-loc-15)
  (= (road-length city-loc-4 city-loc-1) 17)
  (= (road-length city-loc-1 city-loc-4) 17)
  (= (road-length city-loc-4 city-loc-2) 23)
  (= (road-length city-loc-2 city-loc-4) 23)
  (= (road-length city-loc-5 city-loc-2) 16)
  (= (road-length city-loc-2 city-loc-5) 16)
  (= (road-length city-loc-5 city-loc-3) 24)
  (= (road-length city-loc-3 city-loc-5) 24)
  (= (road-length city-loc-6 city-loc-5) 29)
  (= (road-length city-loc-5 city-loc-6) 29)
  (= (road-length city-loc-7 city-loc-2) 28)
  (= (road-length city-loc-2 city-loc-7) 28)
  (= (road-length city-loc-7 city-loc-3) 20)
  (= (road-length city-loc-3 city-loc-7) 20)
  (= (road-length city-loc-7 city-loc-4) 29)
  (= (road-length city-loc-4 city-loc-7) 29)
  (= (road-length city-loc-7 city-loc-5) 21)
  (= (road-length city-loc-5 city-loc-7) 21)
  (= (road-length city-loc-9 city-loc-7) 24)
  (= (road-length city-loc-7 city-loc-9) 24)
  (= (road-length city-loc-9 city-loc-8) 25)
  (= (road-length city-loc-8 city-loc-9) 25)
  (= (road-length city-loc-10 city-loc-3) 18)
  (= (road-length city-loc-3 city-loc-10) 18)
  (= (road-length city-loc-11 city-loc-6) 16)
  (= (road-length city-loc-6 city-loc-11) 16)
  (= (road-length city-loc-12 city-loc-2) 15)
  (= (road-length city-loc-2 city-loc-12) 15)
  (= (road-length city-loc-12 city-loc-4) 14)
  (= (road-length city-loc-4 city-loc-12) 14)
  (= (road-length city-loc-12 city-loc-5) 20)
  (= (road-length city-loc-5 city-loc-12) 20)
  (= (road-length city-loc-12 city-loc-7) 18)
  (= (road-length city-loc-7 city-loc-12) 18)
  (= (road-length city-loc-13 city-loc-2) 22)
  (= (road-length city-loc-2 city-loc-13) 22)
  (= (road-length city-loc-13 city-loc-5) 18)
  (= (road-length city-loc-5 city-loc-13) 18)
  (= (road-length city-loc-13 city-loc-6) 17)
  (= (road-length city-loc-6 city-loc-13) 17)
  (= (road-length city-loc-14 city-loc-2) 29)
  (= (road-length city-loc-2 city-loc-14) 29)
  (= (road-length city-loc-14 city-loc-3) 22)
  (= (road-length city-loc-3 city-loc-14) 22)
  (= (road-length city-loc-14 city-loc-5) 14)
  (= (road-length city-loc-5 city-loc-14) 14)
  (= (road-length city-loc-14 city-loc-6) 21)
  (= (road-length city-loc-6 city-loc-14) 21)
  (= (road-length city-loc-14 city-loc-7) 29)
  (= (road-length city-loc-7 city-loc-14) 29)
  (= (road-length city-loc-14 city-loc-13) 19)
  (= (road-length city-loc-13 city-loc-14) 19)
  (= (road-length city-loc-15 city-loc-3) 25)
  (= (road-length city-loc-3 city-loc-15) 25)
  (= (road-length city-loc-15 city-loc-5) 28)
  (= (road-length city-loc-5 city-loc-15) 28)
  (= (road-length city-loc-15 city-loc-6) 23)
  (= (road-length city-loc-6 city-loc-15) 23)
  (= (road-length city-loc-15 city-loc-10) 24)
  (= (road-length city-loc-10 city-loc-15) 24)
  (= (road-length city-loc-15 city-loc-11) 30)
  (= (road-length city-loc-11 city-loc-15) 30)
  (= (road-length city-loc-15 city-loc-13) 30)
  (= (road-length city-loc-13 city-loc-15) 30)
  (= (road-length city-loc-15 city-loc-14) 15)
  (= (road-length city-loc-14 city-loc-15) 15)
  (visited city-loc-1)
  (next city-loc-1 city-loc-2)
  (next city-loc-2 city-loc-3)
  (next city-loc-3 city-loc-4)
  (next city-loc-4 city-loc-5)
  (next city-loc-5 city-loc-6)
  (next city-loc-6 city-loc-7)
  (next city-loc-7 city-loc-8)
  (next city-loc-8 city-loc-9)
  (next city-loc-9 city-loc-10)
  (next city-loc-10 city-loc-11)
  (next city-loc-11 city-loc-12)
  (next city-loc-12 city-loc-13)
  (next city-loc-13 city-loc-14)
  (next city-loc-14 city-loc-15)
  (origin city-loc-1)
  (last city-loc-15)
  (at city-loc-1)

; START - pure strategies
  (= (cost-check-unvisited-location city-loc-1) 3145)
  (= (cost-check-unvisited-location city-loc-2) 9364)
  (= (cost-check-unvisited-location city-loc-3) 9251)
  (= (cost-check-unvisited-location city-loc-4) 1913)
  (= (cost-check-unvisited-location city-loc-5) 4172)
  (= (cost-check-unvisited-location city-loc-6) 9436)
  (= (cost-check-unvisited-location city-loc-7) 1094)
  (= (cost-check-unvisited-location city-loc-8) 3738)
  (= (cost-check-unvisited-location city-loc-9) 9923)
  (= (cost-check-unvisited-location city-loc-10) 4761)
  (= (cost-check-unvisited-location city-loc-11) 5623)
  (= (cost-check-unvisited-location city-loc-12) 4844)
  (= (cost-check-unvisited-location city-loc-13) 1336)
  (= (cost-check-unvisited-location city-loc-14) 4971)
  (= (cost-check-unvisited-location city-loc-15) 5489)
; END - pure strategies
 )
 (:goal (and
  (goal)
 ))
 (:metric minimize (total-cost))
)
